[package]
name = "bloggy"
version = "0.1.0"
authors = ["Ambrose Chua <1902945@sit.singaporetech.edu.sg>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.5"
